#!/usr/bin/env python3
"""Encode a boot-splash PNG into recomp/src/splash_image.h.

The splash fills the 320x256 logical render area (5:4). It is embedded at the
default-scale window resolution (960x768) so it renders crisp 1:1, encoded
LOSSLESSLY as QOI (qoiformat.org) and base64'd. A ~60-line QOI decoder in
recomp/src/qoi_dec.h expands it at boot -- no external image library.

Usage:  python recomp/tools/splash_to_h.py <splash.png>
"""
import base64, os, sys
from PIL import Image

SRC = sys.argv[1] if len(sys.argv) > 1 else None
if not SRC or not os.path.exists(SRC):
    sys.exit("usage: splash_to_h.py <splash.png>")

W, H = 960, 768
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src", "splash_image.h")

def qoi_encode(rgb, w, h):
    out = bytearray(b'qoif'); out += w.to_bytes(4,'big') + h.to_bytes(4,'big') + bytes([3,0])
    idx = [(0,0,0,0)]*64; pr,pg,pb,pa = 0,0,0,255; run = 0
    for i in range(w*h):
        r,g,b,a = rgb[i*3],rgb[i*3+1],rgb[i*3+2],255
        if (r,g,b,a)==(pr,pg,pb,pa):
            run += 1
            if run==62: out.append(0xC0|(run-1)); run=0
        else:
            if run>0: out.append(0xC0|(run-1)); run=0
            h64=(r*3+g*5+b*7+a*11)&63
            if idx[h64]==(r,g,b,a):
                out.append(h64)
            else:
                idx[h64]=(r,g,b,a)
                dr=((r-pr+128)&255)-128; dg=((g-pg+128)&255)-128; db=((b-pb+128)&255)-128
                if -2<=dr<=1 and -2<=dg<=1 and -2<=db<=1:
                    out.append(0x40|((dr+2)<<4)|((dg+2)<<2)|(db+2))
                else:
                    dgr=((dr-dg+128)&255)-128; dgb=((db-dg+128)&255)-128
                    if -32<=dg<=31 and -8<=dgr<=7 and -8<=dgb<=7:
                        out.append(0x80|(dg+32)); out.append(((dgr+8)<<4)|(dgb+8))
                    else:
                        out.append(0xFE); out += bytes([r,g,b])
        pr,pg,pb,pa = r,g,b,a
    if run>0: out.append(0xC0|(run-1))
    out += bytes([0,0,0,0,0,0,0,1])
    return bytes(out)

im = Image.open(SRC).convert("RGB").resize((W, H), Image.LANCZOS)
qoi = qoi_encode(im.tobytes(), W, H)
b64 = base64.b64encode(qoi).decode("ascii")
body = "\n".join('"%s"' % b64[i:i+120] for i in range(0, len(b64), 120))

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(f"""#ifndef SPLASH_IMAGE_INCLUDED
#define SPLASH_IMAGE_INCLUDED
/* Boot splash -- GENERATED by recomp/tools/splash_to_h.py from an original PNG.
 * {W}x{H}, lossless QOI, base64-encoded ({len(qoi)} QOI bytes -> {len(b64)} b64 chars).
 * Decoded once at boot (base64 -> QOI -> RGB) via qoi_dec.h; see run_sdl in moon.c. */
#define SPLASH_W {W}
#define SPLASH_H {H}
static const char splash_b64[] =
{body};
#endif
""")
print(f"wrote {OUT}: {W}x{H}  QOI={len(qoi)}B  b64={len(b64)} chars")
